demo_sents = [s.lower() for s in [
    "' We all will die '. They said",
    "Vulnerability is not winning or losing; it's having the courage to show up and be seen when we have no control over the outcome. Vulnerability is not weakness; it's our greatest measure of courage.",
    "People don't buy what you do; they buy why you do it. And what you do simply proves what you believe.",
    "Our bodies change our minds, and our minds can change our behavior, and our behavior can change our outcomes. Tiny tweaks can lead to big changes.",
    "We don't grow into creativity, we grow out of it. Or rather, we get educated out of it.",
    "Show a people as one thing, as only one thing, over and over again, and that is what they become. The single story creates stereotypes, and the problem with stereotypes is not that they are untrue, but that they are incomplete.",
    "In the future, there will be no female leaders. There will just be leaders.",
    "We all have a genius inside of us. Creativity is a process, not a destination.",
    "Natural happiness is what we get when we get what we wanted, and synthetic happiness is what we make when we don't get what we wanted. In our society, we have a strong belief that synthetic happiness is of an inferior kind.",
    "We are losing our listening. We spend roughly 60 percent of our communication time listening, but we're not very good at it.",
    "We have the solutions we need to solve this crisis. All we need is the political will, but political will is a renewable resource.",
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "Life is what happens when you're busy making other plans.",
    "Keep your face always toward the sunshine, and shadows will fall behind you.",
    "The best way to predict your future is to create it.",
    "You miss 100 percent of the shots you don't take.",
    "Don't watch the clock; do what it does. Keep going.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "It always seems impossible until it's done.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "You are never too old to set another goal or to dream a new dream.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Dream big and dare to fail.",
    "Success is not in what you have, but who you are.",
    "Act as if what you do makes a difference. It does.",
    "What we think, we become.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "Turn your wounds into wisdom.",
    "Your time is limited, so don't waste it living someone else's life."
]]